version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/freckles
    binary: freckles
    tags:
      - release
archives:
  -
    name_template: '{{ .Binary }}_{{ .Version }}_termux_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

brews:
  -
    name: freckles
    description: "simple dotfiles manager"
    homepage: "https://github.com/rsteube/freckles"
    license: "MIT"
    repository:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
scoops:
  -
    description: "simple dotfiles manager"
    homepage: "https://github.com/rsteube/freckles"
    license: "MIT"
    repository:
      owner: rsteube
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

aurs:
  -
    description: "simple dotfiles manager"
    homepage: "https://github.com/rsteube/freckles"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/freckles-bin.git'
    depends:
      - 'git'
    optdepends:
      - 'carapace-bin: for git completion'
      - 'github-cli: for github completion'

nfpms:
  -
    description: "simple dotfiles manager"
    homepage: "https://github.com/rsteube/freckles"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
