version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /freckles/cmd/freckles  && go build -ldflags=\"-s -w\" -buildvcs=false ."'
    volumes:
      - '.:/freckles/'
      - 'go:/go/'

  elvish:
    build: .
    command: elvish
    volumes:
      - "$HOME/.config/gh:/root/.config/gh:ro"
      - "$HOME/.ssh:/root/.ssh:ro"
      - '.:/freckles/'

volumes:
  go:
