version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /freckles-bin/cmd/freckles  && go build -ldflags=\"-s -w\" ."'
    volumes:
      - '.:/freckles-bin/'
      - 'go:/go/'

  elvish:
    build: .
    command: elvish
    volumes:
      - '.:/freckles-bin/'

volumes:
  go:
