version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /dotfiles-bin/cmd/dotfiles  && go build -ldflags=\"-s -w\" ."'
    volumes:
      - '.:/dotfiles-bin/'
      - 'go:/go/'

  elvish:
    build: .
    command: elvish
    volumes:
      - '.:/dotfiles-bin/'

volumes:
  go:
